### ISSUE TITLE
Echelon and text wrong placement

### ISSUE THREAD

**Issue by salexgit** [ralphieraccoon/MilSymb#14]
Hi

I tried to use this LaTeX package and have immediately faced the issue that symbol echelon and text information is rendered in wrong location. I have attached an archive with a simple Tex file and resulting DVI output. As you can see, echelon and text data from all the symbols is placed at the same location irrespective of the symbol they belong to. 

[test.zip](https://github.com/ralphieraccoon/MilSymb/files/3290321/test.zip)

Since it works for you, I assume that it could be due to different package versions.

Regards, Alex

**Comment by ralphieraccoon** [comment]
Hi,

This looks like an issue with DVI, as `tikz` uses special postscript code to which DVI cannot render properly. 

See [this](https://tex.stackexchange.com/questions/84182/tikz-pgf-figures-messed-in-dvi) Tex.SE question for further details, it looks exactly like your problem, there are some solutions you can try if you have to render to DVI for whatever reason, but I would suggest compiling straight to PDF if at all possible. Unfortunately this looks like something that can't be fixed on my end, so I'll close the issue.

**Comment by salexgit** [comment]
Hi

Thanks for the hint. I tried to compile straight to PDF, and it worked. 
Maybe you consider adding some "build instructions" into the documentation so that people know that DVI is not supported properly.

**Comment by ralphieraccoon** [comment]
Can possibly add a sentence to section 1.3. Thanks.
