### ISSUE TITLE
Full path to multi symbols 

### ISSUE THREAD

**Issue by salexgit** [ralphieraccoon/MilSymb#15]
Hi 

This is not really MilSymb package problem, but something inside the MilSymb package or dependent packages trigger it. So, I have been trying to use the custom icon following an example from the documentation.

\makeatletter
\tikzset{
  MilSymb custom/armoured recon/.pic={
    \pic{MilSymb custom/tank};
    \pic{MilSymb land/main/reconnaissance/\MilSymb@selectedfaction};
  }
}
\makeatother

However, the moment I try to use, I got the following error message. Any clue what could be the reason?

"Tex capacity exceeded, sorry [grouping levels=255]..."

Regards, Alex

**Comment by ralphieraccoon** [comment]
Hi,

Can you send me the entire file you're trying to compile?

Thanks

**Comment by salexgit** [comment]
Hi

Thanks a lot for a quick response! 
Here is the .tex file. Everything works fine except custom icons. I defined a custom icon called "armoured recon", but whenever I actually try to use it, I got that error message.

[test.tex.zip](https://github.com/ralphieraccoon/MilSymb/files/3298466/test.tex.zip)

Regards, Alex

**Comment by ralphieraccoon** [comment]
Hi,

I've been unable to replicate your error using pdfLaTeX or Latexmk, it seems to compile fine for me with the custom icons. Are you restricting memory usage at all? That's the only thing I can think of, but that's usually a slightly different error message.

P.S. I noticed the serif font appeared to be rastered. This is a bug, I think I've got a fix for it so I'll push that out shortly.

**Comment by salexgit** [comment]
Hi

Thanks a lot for your help! I checked the log and it turned out that the root cause was completely different. So, the following code worked for me and I was able to get icon I wanted:

\makeatletter
\tikzset{
  MilSymb custom/armoured recon/.pic={
    \draw circle(0.5 and 0.15);
    \clip \clipfriendly;
    \pic{MilSymb land/main/reconnaissance/\MilSymb@selectedfaction};
  }
}
\makeatother

However, any attempt to use "land/main/armoured" was failing. What is wrong with the following code? Error log says that "! Package pgfkeys Error: I do not know the key '/tikz/pics/MilSymb land/main/ar
moured/friendly' and I am going to ignore it. Perhaps you misspelled it."

\makeatletter
\tikzset{
  MilSymb custom/armoured recon/.pic={
    \pic{MilSymb land/main/armoured/\MilSymb@selectedfaction};
    \clip \clipfriendly;
    \pic{MilSymb land/main/reconnaissance/\MilSymb@selectedfaction};
  }
}
\makeatother

Regards, Alex

**Comment by salexgit** [comment]
Hi

Did you have time to take a look at this issue? In short, I can use various equipment/main icons, such as machine gun, anti tank, etc. However, whenever I try to use "main/armoured", it gives me an error.

Regards, Alex

Regards, Alex

**Comment by ralphieraccoon** [comment]
Hi, sorry I've got a lot of deadlines with work this week. I should be able to take a look at it in July.

**Comment by salexgit** [comment]
Hi

Ok, I managed to solve it. The problem is that documentation section 3.6.2 refers to icons as "main/xxx", whereas the full path should be "multi/main/xxx". That is why all my attempts to use "main/armoured" were failing.
Please note that it logically contradicts to section 3.6.3, in which the full path is given, e.g. "equipment/main/xxx"; and it works as expected. 

I would recommend updating the documentation accordingly.

Regards, Alex

**Comment by ralphieraccoon** [comment]
Hi!

It is specified in the introduction in 3.6.2 that they are all in the same directory called `multi`. The reason the full path is given in 3.6.3 is that they are in different directories. However, I can see how this might be confusing, and to reinforce the point I'll put the full path in 3.6.2 as well.

Thanks

- Ralphie

**Comment by salexgit** [comment]
Hi

The full path will be really helpful because it was not obvious that you need to add "multi" to make the correct full path. I almost gave up - but then I checked the source .tex file and realised that I had to add multi. I can easily imagine somebody else struggling with the same problem :)

Regards, Alex

**Comment by ralphieraccoon** [comment]
Fixed in #3599edaefc1d0a8edce794e62a482906d07d6e13.
